### ISSUE TITLE
pip install fails with "failed to build twisted" - missing longintrepr.h

### ISSUE THREAD

**Issue by dwreski** [DanMcInerney/xsscrapy#82]
Running "pip install -r requirements.txt" on fedora38 fails with the message below. It's looking for longintrepr.h but can't find it.

$ rpm -qf /usr/include/python3.11/cpython/longintrepr.h
python3-devel-3.11.8-1.fc38.x86_64

```
      gcc -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC -I/usr/include/python3.11 -c src/twisted/test/raiser.c -o build/temp.linux-x86_64-cpython-311/src/twisted/test/raiser.o
      src/twisted/test/raiser.c:49:12: fatal error: longintrepr.h: No such file or directory
         49 |   #include "longintrepr.h"
            |            ^~~~~~~~~~~~~~~
      compilation terminated.
      error: command '/usr/lib64/ccache/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for twisted
  Running setup.py clean for twisted
Failed to build twisted

```

**Comment by xcalibure2** [comment]
try to remove the version specification from requirements.txt for twisted.
but It does not seem to work with python 3.11.

**Comment by dwreski** [comment]
That worked - now it's complaining about missing urlparse. It looks like it was changed to urllib recently?
https://stackoverflow.com/questions/48072619/how-can-i-import-urlparse-in-python-3
